[build]
  command = "next build"
  publish = ".next"
  base = ""

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLE = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true